### ISSUE TITLE
Having build error

### ISSUE THREAD

**Issue by AndroidDeveloperLB** [mtsahakis/MediaProjectionDemo#11]
When importing and trying to build the sample project, I get this error:

> Information:Gradle tasks [:app:assembleDebug]
> C:\Users\User\Desktop\android-hidden-api\sample\android-hidden-api\src\main\java\com\anggrayudi\hiddenapi\InternalAccessor.java
> Error:(43, 73) error: package com.android.internal.R does not exist
> Error:(44, 73) error: package com.android.internal.R does not exist
> Error:(45, 73) error: package com.android.internal.R does not exist
> Error:(46, 73) error: package com.android.internal.R does not exist
> Error:(47, 73) error: package com.android.internal.R does not exist
> Error:(48, 73) error: package com.android.internal.R does not exist
> Error:(49, 73) error: package com.android.internal.R does not exist
> Error:(50, 73) error: package com.android.internal.R does not exist
> Error:(51, 73) error: package com.android.internal.R does not exist
> Error:(52, 73) error: package com.android.internal.R does not exist
> Error:(53, 73) error: package com.android.internal.R does not exist
> Error:(54, 73) error: package com.android.internal.R does not exist
> Error:(55, 73) error: package com.android.internal.R does not exist
> Error:(56, 73) error: package com.android.internal.R does not exist
> Error:(57, 73) error: package com.android.internal.R does not exist
> Error:(58, 73) error: package com.android.internal.R does not exist
> Error:org.gradle.api.internal.tasks.compile.CompilationFailedException: Compilation failed; see the compiler error output for details.

**Comment by mtsahakis** [comment]
Should be ok with latest Android Studio 2.3.1 I just updated build targets. Update the project and possibly do a clean build.

**Comment by AndroidDeveloperLB** [comment]
Wrote it in the wrong repo (see package name). Sorry

**Comment by AndroidDeveloperLB** [comment]
Can you please remove this whole thread?
