### ISSUE TITLE
Question: Any way to get Frames as per FPS

### ISSUE THREAD

**Issue by Nik2505** [mtsahakis/MediaProjectionDemo#13]
Is there any way to get frames or images as per frame per second?

**Comment by ShaheryarMalik007** [comment]
kdsjf

**Comment by ShaheryarMalik007** [comment]
use a boolean 
like 
takeImage = false:

on start record make it true,

and on imageAvailable check it if its true,

once you have taken and image  make it false and stopRecording()

**Comment by mtsahakis** [comment]
This is a bit tricky, as the ImageReader might stop returning images, so your FPS might drop to zero if nothing is going on on the screen.
