### ISSUE TITLE
onImageAvailable not called

### ISSUE THREAD

**Issue by Charlesjean** [mtsahakis/MediaProjectionDemo#2]
I find this method is never called on my Nexus5, my os is 5.0

**Comment by mtsahakis** [comment]
I use Nexus 7 and it does call onImageAvailable but I can't really say whats going on your device. 
Have you tried on an alternative device or 5.0+ emulator?

**Comment by mtsahakis** [comment]
Followed your recommendation in SOF http://stackoverflow.com/questions/26673127/android-imagereader-acquirelatestimage-returns-invalid-jpg and updated the project accordingly. Many thanks!
