### ISSUE TITLE
Request: please show how to capture videos and even with audio

### ISSUE THREAD

**Issue by AndroidDeveloperLB** [mtsahakis/MediaProjectionDemo#20]
Seems it's possible on Android Q.

**Comment by mgood7123** [comment]
> Seems it's possible on Android Q.

thats ONLY cus that feature (specifically the Device audio (NOT MIC) recording) is ONLY available on Q as Built-In (eg System/OS level feature)

**Comment by AndroidDeveloperLB** [comment]
It's not only for built in apps. It's available for third party apps too, such as this one:

https://play.google.com/store/apps/details?id=com.kimcy929.screenrecorder

**Comment by mtsahakis** [comment]
This is beyond the scope of this sample app. Feel free to extend it, I am open to PRs.
