### ISSUE TITLE
Can we record screen in service ?

### ISSUE THREAD

**Issue by tmehta813** [mtsahakis/MediaProjectionDemo#21]
As in my app we don't have any activity,
Can we record screen in service ?

**Comment by mtsahakis** [comment]
I had done something similar at some point, see

https://gist.github.com/mtsahakis/a4dca46b80cb8ac2cd100a7a52f65b1d
https://gist.github.com/mtsahakis/5c709bbd9cf5074a377e6e3114c0e4b6

Hope it helps,

Manos

**Comment by tmehta813** [comment]
Thank you for you response, Can we also control it from notification?

**Comment by mtsahakis** [comment]
I would assume so, just start the service from the notification https://stackoverflow.com/questions/6422319/start-service-from-notification

**Comment by Rich2020** [comment]
Hmm, my code won't compile when I use `PixelFormat.RGBA_8888`. I have to change to ImageFormat, but then I get exceptions when `image = mImageReader.acquireLatestImage();`. I've been through all the comments in a [SO post that you created](https://stackoverflow.com/q/26673127/596841), but it is still not working for me. I'd love it if you can take a look and give me a hand. Thanks!

**Comment by mtsahakis** [comment]
It should compile as it is just a warning. I added a @SuppressLint("WrongConstant") annotation. If you look into the source code of ImageReader, it states 

`* @param format The format of the Image that this reader will produce. This
  *            must be one of the {@link android.graphics.ImageFormat} or
  *            {@link android.graphics.PixelFormat}`

So could be something wrong with the @Format annotation.
