### ISSUE TITLE
I use the code on Android 6.0 emulator, capture screen image is all black

### ISSUE THREAD

**Issue by arvidhu** [mtsahakis/MediaProjectionDemo#5]

**Comment by mtsahakis** [comment]
Hi,

I think the issue might be linked to:
http://stackoverflow.com/questions/33046375/e-surface-getslotfrombufferlocked-unknown-buffer-0xab7519c0/33898248
http://stackoverflow.com/questions/32561479/android-studio-getslotfrombufferlocked-unknown-buffer-error?lq=1

If that is the case, then it is Marshmallow 6.0 issue. 

I installed the app on an Android M emulator and observed the patch level to be March 2015, far behind the latest patch level of 6.0.1 of May 2016. I installed the app on a Nexus 7 with Android M 6.0.1 May 2016 and everything is working fine. I even tried it on a Nexus 10 with Android N beta preview and works fine.

I would recommend to install the app on a range of devices running Lollipop 5.0.1 (API 21), Lollipop 5.1.1 (API 22), Marshmallow 6.0.1 (API 23), Android N beta, and if you face any issues let me know. If you are running on a 5.1 device, be aware of this https://code.google.com/p/android/issues/detail?id=159613 runtime exception that was patched at 5.1.1.

As far as the emulator goes, if you come up with a workaround I am more than willing to accept it as a patch.

Thank you,

Manos

**Comment by arvidhu** [comment]
Hi Manos, 
Today morning, I test the demo code on Nexus 9, it work well. I have use 3 days on the emulator(android studio 6.0 and DuOS android 5.0), now I know the emulator support MediaProjection uncompletely.
when I come here to say this, you have give quick reply, thank you very much.

Arvid Hu

**Comment by mtsahakis** [comment]
Hi,
I tried with various emulators (5.0, 5.1, 6.0) but I am always getting a black screen. You are right, I do not think emulator support is there. I will update README section to reflect this.

Thank you,
Manos
